/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/a7d5fab8-1e67-4ec0-a3f9-357c76d78f04 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float tep;
  float vlh;
  bool lED_Status_1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information youâll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  /*
  ArduinoCloud.update();
  // Your code here 
  LED_Online_1 = true;
  delay(1000);
  ArduinoCloud.update();
  LED_Online_1 = false;
  delay(1000);
  */

  ArduinoCloud.updateProperty(LED_Online_1,true);
  delay(1000);
  ArduinoCloud.updateProperty(LED_Online_1,false);
  delay(1000);
}






