// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "34071f27-b100-48f2-82a2-0426fe04a515";

const char SSID[] = "DESKTOP-IF5CDUO";    // Network SSID (name)
const char PASS[] = "123456789";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "UK3FIVSPEQUB6TJ5UEOQ";    // Secret device password


float tep1;
float vlh1;
bool LED_Err_1;
bool LED_Online_1;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(tep1, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(vlh1, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(LED_Err_1, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(LED_Online_1, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
